apiVersion: apps/v1
kind: Deployment
metadata:
  name: switcher-ac
spec:
  replicas: 1
  selector:
    matchLabels:
      app: switcher-ac
  template:
    metadata:
      labels:
        app: switcher-ac
    spec:
      dnsPolicy: Default
      containers:
        - name: switcher-ac
          image: trackerforce/switcher-ac:latest
          ports:
            - containerPort: 8070
              protocol: TCP
          resources: 
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
          - name: SPRING_PROFILES_ACTIVE
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SPRING_PROFILES_ACTIVE
          - name: GITHUB_CLIENTID
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: GITHUB_CLIENTID

          # Secrets
          - name: API_SECRET
            valueFrom:
              secretKeyRef:
                name: switcher-ac
                key: API_SECRET
          - name: RELAY_TOKEN
            valueFrom:
              secretKeyRef:
                name: switcher-ac
                key: RELAY_TOKEN
          - name: GITHUB_SECRET
            valueFrom:
              secretKeyRef:
                name: switcher-ac
                key: GITHUB_SECRET
          - name: MONGODB_URL
            valueFrom:
              secretKeyRef:
                name: switcher-ac
                key: MONGODB_URL
          - name: ADMIN_USER
            valueFrom:
              secretKeyRef:
                name: switcher-ac
                key: ADMIN_USER
          - name: ADMIN_PASS
            valueFrom:
              secretKeyRef:
                name: switcher-ac
                key: ADMIN_PASS
          - name: SWITCHER_KEY
            valueFrom:
              secretKeyRef:
                name: switcher-ac
                key: SWITCHER_KEY

          # Switcher API Client
          - name: SWITCHER_URL
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SWITCHER_URL
          - name: SWITCHER_DOMAIN
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SWITCHER_DOMAIN
          - name: SWITCHER_ENV
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SWITCHER_ENV
          - name: SWITCHER_SNAPSHOT_LOCATION
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SWITCHER_SNAPSHOT_LOCATION
          - name: SWITCHER_SNAPSHOT_AUTO
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SWITCHER_SNAPSHOT_AUTO
          - name: SWITCHER_OFFLINE
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SWITCHER_OFFLINE
          - name: SWITCHER_SILENT
            valueFrom:
              configMapKeyRef:
                name: switcher-ac
                key: SWITCHER_SILENT