apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- digest: sha256:3b2b1d62805e3c2ffe5caf158e742c77c3d71f3ccb198b2718c1958a10dfb322
  name: trackerforce/switcher-ac:latest
  newName: trackerforce/switcher-ac
