apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: trackerforce/switcher-ac:latest
  digest: sha256:983293e8abe6906014b95b59635d38f38e306b32c7c218348818f69bf150ba36