apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- digest: sha256:4d2d4465370b659ca73ad397b3b14a1a997b0eb832eef15a09db013f3b442403
  name: trackerforce/switcher-ac:latest
  newName: trackerforce/switcher-ac
