apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- digest: sha256:b8005fd9d302e63f51411dd93fc9dbc1b55a986358740616cf081ffa29c528c7
  name: trackerforce/switcher-ac:latest
  newName: trackerforce/switcher-ac
