apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- digest: sha256:cb45ecaaa1d56c308db68934d2903ffd2f75b0c1f31203ae11ebb1807e779343
  name: trackerforce/switcher-ac:latest
  newName: trackerforce/switcher-ac
