apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- digest: sha256:03e7126b5af1a2eda5b7d84f4b94f1015865fab8ab77edd3e6e9128affa1bd5e
  name: trackerforce/switcher-ac:latest
  newName: trackerforce/switcher-ac
