apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

images:
- name: trackerforce/switcher-api-dev:latest
  newName: trackerforce/switcher-api-dev
  newTag: latest
