apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

images:
- digest: sha256:92444339ddf472519a5b4ecf4fb001f7b5332bc6116b78f158f472eea17b3e35
  name: trackerforce/switcher-slack-app:latest
  newName: trackerforce/switcher-slack-app
