apiVersion: apps/v1
kind: Deployment
metadata:
  name: switcher-api
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: switcher-api
  template:
    metadata:
      labels:
        app: switcher-api
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - worker-0
      containers:
        - name: switcher-api
          image: trackerforce/switcher-api:latest
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: 
            requests:
              memory: "256Mi"
              cpu: "200m"
            limits:
              memory: "256Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /check
              port: 3000
          env:
          - name: PORT
            value: "3000"
          - name: RELEASE_TIME
            valueFrom:
              configMapKeyRef:
                name: switcher-api-generated
                key: RELEASE_TIME
          envFrom:
            - secretRef:
                name: switcher-api
            - configMapRef:
                name: switcher-api