apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- envs:
  - environment-properties.env
  name: switcher-api-generated

images:
- digest: sha256:d09af6506ca27eea9e3a248b210acaa7e9305131bb8ddf6d6d30608b647a885b
  name: trackerforce/switcher-api:latest
  newName: trackerforce/switcher-api
