apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- envs:
  - environment-properties.env
  name: switcher-api-generated

images:
- digest: sha256:82608bfb28d48f8cb3128bbce5b3f92700784c42a1fee53457912eddf7eed564
  name: trackerforce/switcher-api:latest
  newName: trackerforce/switcher-api
