apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- behavior: replace
  envs:
  - environment-properties.env
  name: switcher-api-generated

images:
- digest: sha256:ffa32d423891186440505021570021a91124dd5ff602ecc13b0f92f0008539df
  name: trackerforce/switcher-api:latest
  newName: trackerforce/switcher-api
