apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- envs:
  - environment-properties.env
  name: switcher-management-generated

images:
- digest: sha256:332432da361fdc9b75f3a86d113a4e2948d3793600760de5b4c441c356fb79ba
  name: trackerforce/switcher-management:latest
  newName: trackerforce/switcher-management
