apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- envs:
  - environment-properties.env
  name: switcher-management-generated

images:
- digest: sha256:4a6705efecafdb2100a5161288b12cae7edf91fca27b115f9842d26438f98210
  name: trackerforce/switcher-management:latest
  newName: trackerforce/switcher-management
