apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- name: switcher-management-generated
  envs:
  - environment-properties.env

images:
- digest: sha256:1e20aef166b3456d5240fc1ad953096e1b3642abcf63a163ee4b45e807014944
  name: trackerforce/switcher-management:latest
  newName: trackerforce/switcher-management
