apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- envs:
  - environment-properties.env
  name: switcher-management-generated

images:
- digest: sha256:dd5db212e2d391647400e3e881f99d7239508fbdcdd10a5f0aa406be497f06be
  name: trackerforce/switcher-management:latest
  newName: trackerforce/switcher-management
