apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- ingress.yaml
- service.yaml

configMapGenerator:
- envs:
  - environment-properties.env
  name: switcher-management-generated

images:
- digest: sha256:98755782f95334cd6cf1389998ec1d26b98d9e10ee17ca387a318058c9f71b11
  name: trackerforce/switcher-management:latest
  newName: trackerforce/switcher-management
