apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml

configMapGenerator:
- behavior: create
  envs:
  - environment-properties.env
  name: switcher-management-generated

images:
- digest: sha256:89e90c865b94a623f46cfd189b42b99941b7337a72d7aab8e202942eb949bada
  name: trackerforce/switcher-management:latest
  newName: trackerforce/switcher-management
